FarmBot/Software/Farmbot-Web-App/config/routes.rb
FarmBot::Application.routes.draw do
  namespace :api, defaults: { format: :json }, constraints: { format: "json" } do
    post "/rmq/user" => "rmq_utils#user_action", as: "rmq_user"
    post "/rmq/vhost" => "rmq_utils#vhost_action", as: "rmq_vhost"
    post "/rmq/resource" => "rmq_utils#resource_action", as: "rmq_resource"
    post "/rmq/topic" => "rmq_utils#topic_action", as: "rmq_topic"

    # Standard API Resources:
    {
      alerts: [:create, :destroy, :index],
      diagnostic_dumps: [:create, :destroy, :index],
      farm_events: [:create, :destroy, :index, :show, :update],
      farmware_envs: [:create, :destroy, :index, :show, :update],
      first_party_farmwares: [:show, :index],
      global_bulletins: [:show],
      images: [:create, :destroy, :index, :show],
      password_resets: [:create, :update],
      peripherals: [:create, :destroy, :index, :show, :update],
      pin_bindings: [:create, :destroy, :index, :show, :update],
      plant_templates: [:create, :destroy, :index, :update],
      point_groups: [:index, :create, :update, :destroy],
      regimens: [:create, :destroy, :index, :show, :update],
      sensor_readings: [:create, :destroy, :index, :show],
      sensors: [:create, :destroy, :index, :show, :update],
      sequences: [:create, :destroy, :index, :show, :update],
      tools: [:create, :destroy, :index, :show, :update],
      webcam_feeds: [:create, :destroy, :index, :show, :update],
    }.to_a.map { |(name, only)| resources name, only: only }

    # Singular API Resources:
    {
      demo_account: [:create],
      device_cert: [:create],
      device: [:create, :destroy, :show, :update],
      fbos_config: [:destroy, :show, :update],
      firmware_config: [:destroy, :show, :update],
      public_key: [:show],
      tokens: [:create, :show],
      web_app_config: [:destroy, :show, :update],
    }.to_a.map { |(name, only)| resource name, only: only }
    get "/corpus" => "corpuses#show", as: :api_corpus

    resources(:points, except: []) { post :search, on: :collection }

    resources :farmware_installations, except: [:update] do
      post :refresh, on: :member
    end

    resources :logs, except: [:update, :show] do
      # When farmware fetching fails and the user
      # wants to try again.
      get :search, on: :collection
    end

    resource :users, except: [:index] do
      post :resend_verification, on: :member
      post :control_certificate, on: :collection
    end

    resources :saved_gardens, except: [:show] do
      post :snapshot, on: :collection
      post :apply, on: :member
      patch :apply, on: :member
    end

    get "/global_config" => "global_config#show", as: :global_config
    get "/device/sync" => "devices#sync", as: :device_sync
    post "/device/seed" => "devices#seed", as: :device_seed
    post "/device/reset" => "devices#reset", as: :device_reset

    # Make life easier on API users by not adding special rules for singular
    # resources.
    # Might be safe to remove now with the advent of TaggedResource.kind
    get "/device/:id" => "devices#show", as: :get_device_redirect
    patch "/device/:id" => "devices#update", as: :patch_device_redirect
    put "/device/:id" => "devices#update", as: :put_device_redirect

    delete "/fbos_config/:id" => "fbos_configs#destroy", as: "delete_fbos_config_redirect"
    get "/fbos_config/:id" => "fbos_configs#show", as: "get_fbos_config_redirect"
    put "/fbos_config/:id" => "fbos_configs#update", as: "put_fbos_config_redirect"

    delete "/firmware_config/:id" => "firmware_configs#destroy", as: "delete_firmware_config_redirect"
    get "/firmware_config/:id" => "firmware_configs#show", as: "get_firmware_config_redirect"
    patch "/firmware_config/:id" => "firmware_configs#update", as: "patch_firmware_config_redirect"
    put "/firmware_config/:id" => "firmware_configs#update", as: "put_firmware_config_redirect"

    delete "/web_app_config/:id" => "web_app_configs#destroy", as: "delete_web_app_config_redirect"
    get "/web_app_config/:id" => "web_app_configs#show", as: "get_web_app_config_redirect"
    patch "/web_app_config/:id" => "web_app_configs#update", as: "patch_web_app_config_redirect"
    put "/web_app_config/:id" => "web_app_configs#update", as: "put_web_app_config_redirect"

    patch "/users/:id" => "users#update", as: :patch_users_redirect
    put "/users/:id" => "users#update", as: :put_users_redirect

    patch "/webcam_feed/:id" => "webcam_feeds#update", as: :patch_webcam_feed_redirect
    put "/webcam_feed/:id" => "webcam_feeds#update", as: :put_webcam_feed_redirect

    put "/password_resets" => "password_resets#update", as: :whatever
    get "/storage_auth" => "images#storage_auth", as: :storage_auth
    post "/export_data" => "devices#dump", as: :dump_device
  end

  devise_for :users

  # =======================================================================
  # NON-API (USER FACING) URLS:
  # =======================================================================
  get "/" => "dashboard#front_page", as: :front_page

  get "/app" => "dashboard#main_app", as: :dashboard
  get "/app/controls" => "dashboard#main_app", as: :app_landing_page
  get "/app/messages" => "dashboard#main_app", as: :app_message_center
  match "/app/*path", to: "dashboard#main_app", via: :all, constraints: { format: "html" }

  get "/demo" => "dashboard#demo", as: :demo_main
  get "/password_reset/*token" => "dashboard#password_reset", as: :password_reset
  get "/tos_update" => "dashboard#tos_update", as: :tos_update
  get "/verify/:token" => "dashboard#confirmation_page", as: :confirmation_page
  post "/csp_reports" => "dashboard#csp_reports", as: :csp_report
  post "/direct_upload" => "dashboard#direct_upload", as: :direct_upload
end

FarmBot/Software/Farmbot-Web-App/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_global_config
  layout "dashboard"

  # === THESE CONSTANTS ARE CONFIGURABLE: ===
  EVERY_STATIC_PAGE = [:front_page,
                       :main_app,
                       :password_reset,
                       :tos_update,
                       :demo]

  OUTPUT_URL = "/" + File.join("assets", "parcel") # <= served from public/ dir
                                                   # <= See PUBLIC_OUTPUT_DIR
  CACHE_DIR = File.join(".cache")

  CSS_INPUTS = {
    front_page: "/css/laptop_splash.scss",
    default: "/css/_index.scss",
  }.with_indifferent_access

  JS_INPUTS = {
    main_app: "/entry.tsx",
    front_page: "/front_page/index.tsx",
    password_reset: "/password_reset/index.tsx",
    tos_update: "/tos_update/index.tsx",
    demo: "/demo/index.tsx",
  }.with_indifferent_access

  # === THESE CONSTANTS ARE NON-CONFIGURABLE. ===
  # They are calculated based on config above.

  RELEASE_CHUNK = GlobalConfig::LONG_REVISION == "NONE" ?
    SecureRandom.hex.first(5) : GlobalConfig::LONG_REVISION
  CACHE_BUST_STRING = "?version=#{RELEASE_CHUNK}"
  PUBLIC_OUTPUT_DIR = File.join("public", OUTPUT_URL)

  CSS_OUTPUTS = CSS_INPUTS.reduce({}) do |acc, (k, v)|
    file = v.gsub(/\.scss$/, ".css")
    acc[k] = File.join(OUTPUT_URL, file)
    acc
  end.with_indifferent_access

  JS_OUTPUTS = JS_INPUTS.reduce({}) do |acc, (k, v)|
    file = v.gsub(/\.tsx?$/, ".js")
    acc[k] = File.join(OUTPUT_URL, file)
    acc
  end.with_indifferent_access

  PARCEL_ASSET_LIST = (CSS_INPUTS.values + JS_INPUTS.values)
    .sort
    .uniq
    .map { |x| File.join("frontend", x) }
    .join(" ")

  PARCEL_HMR_OPTS = [
    "--no-hmr",
    "--no-cache",
  ].join(" ")

  EVERY_STATIC_PAGE.map do |actn|
    define_method(actn) do
      begin
        # If you don't do this, you will hit hard to debug
        # CSP errors on local when changing API_HOST.
        response.headers["Cache-Control"] = "no-cache, no-store"
        response.headers["Pragma"] = "no-cache"
        response.headers["Expires"] = "0"
        load_css_assets
        load_js_assets
        render actn
      rescue ActionView::MissingTemplate => q
        raise ActionController::RoutingError, "Bad URL in dashboard. -Rick"
      end
    end
  end

  def confirmation_page
    load_css_assets
    user = User.find_by!(confirmation_token: params.fetch(:token))
    # Two use cases:                  re-confirmation   Email change
    klass = user.unconfirmed_email? ? Users::Reverify : Users::Verify
    @token = klass.run!(user: user).to_json
    render :confirmation_page
  rescue User::AlreadyVerified
    @already_registered = true
    render :confirmation_page, status: 409
  end

  # Endpoint reports CSP violations, indicating a possible security problem.
  def csp_reports
    payload = request.body.read || ""
    begin
      report = JSON.parse(payload)
    rescue
      report = { problem: "Crashed while parsing report" }
    end
    Rollbar.info("CSP Violation", report)

    render json: report
  end

  # (for self hosted users) Direct image upload endpoint.
  # Do not use this if you use GCS- it will slow your app down.
  def direct_upload
    raise "No." unless Api::ImagesController.store_locally
    name = params.fetch(:key).split("/").last
    path = File.join("public", "direct_upload", "temp", name)
    File.open(path, "wb") { |f| f.write(params[:file]) }
    render json: ""
  end

  private

  def load_css_assets
    @css_assets ||= [action_name, :default].reduce([]) do |list, action|
      asset = CSS_OUTPUTS[action] # Not every endpoint has custom CSS.
      list.push(asset + CACHE_BUST_STRING) if asset
      list
    end
  end

  def load_js_assets
    # Every DashboardController has a JS SBundle.
    @js_assets ||=
      [JS_OUTPUTS.fetch(action_name)].map { |x| x + CACHE_BUST_STRING }
  end

  def set_global_config
    @global_config = GlobalConfig.dump.to_json
  end
end

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/_common_assets.html.erb
<meta charset="UTF-8">
<meta name="Pragma" content="no-cache">
<meta name="Expires" content="0">
<META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
<title>FarmBot</title>
<script>
<%# IMPORTANT!!!! %>
<%# ALWAYS LOAD THIS *FIRST* %>
window.globalConfig = <%= raw(@global_config) %> // SEE COMMENTS!;
<%# READ COMMENT ABOVE %>
window.process = {
  env: {
    NODE_ENV: <%= raw(Rails.env.inspect) %>
  }
}
</script>
<%= render "addons" %>
<%= javascript_include_tag *@js_assets %>
<meta content="width=device-width, initial-scale=1" name="viewport">
<link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/confirmation_page.html.erb
<div id="root">
  <div class="static-page">
    <div class="all-content-wrapper">
      <h1 class="text-center">
        Account verification
      </h1>
      <br>
      <div class="row">
        <div class="col-xs-12">
          <div class="widget-wrapper">
            <div class="widget-header">
              <h5>
                <% if @already_registered %>
                  Already verified
                <% else %>
                  Verification success
                <% end %>
              </h5>
            </div>
            <div class="widget-body">
              <div class="row">
                <div class="col-xs-12">
                  <% if @already_registered %>
                    You have already verified your account.
                    Please <%= link_to "log in", "/" %>.
                  <% else %>
                    You are now being <%= link_to "redirected", app_message_center_path %>.
                    <script>
                      localStorage.session = JSON.stringify(<%= raw @token %>);
                      window.location.replace("<%= app_message_center_path %>");
                    </script>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/demo.html.erb
<% content_for :head do %>
  <style>
@media screen and (min-width: 769px) {
	.demo-phone {
		display: none;
		height: auto;
	}
}

@media screen and (max-width: 768px) {
	.demo-video {
		display: none;
	}
}

.demo-phone {
   width: 363px;
   height: 726px;
}

.demo-container {
	display: flex;
	justify-content: center;
	position: relative;
	width: 100%;
}

.demo-video {
	opacity: 0.99;
	width: 100%;
}

.demo-button {
	animation: bounce 4s infinite;
	background-color: #489fe4;
	border: none;
	border-radius: 5px;
	bottom: 30px;
	box-shadow: 0 0 15px rgba(0,0,0,0.4);
	color: #fff;
	font-family: "Roboto", sans-serif;
	font-size: 25px;
	font-weight: bold;
	padding: 15px 30px;
	position: absolute;
}

.demo-button:hover {
	background-color: #287dc1;
	cursor: pointer;
}

@-moz-keyframes bounce {
	10%, 26%, 40%, 0%, 50% {
		animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
		transform: translate3d(0, 0, 0);
	}

	20%, 21% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -8px, 0);
	}

	35% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -5px, 0);
	}

	45% {
		transform: translate3d(0, -2px, 0);
	}
}

@-webkit-keyframes bounce {
	10%, 26%, 40%, 0%, 50% {
		animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
		transform: translate3d(0, 0, 0);
	}

	20%, 21% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -8px, 0);
	}

	35% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -5px, 0);
	}

	45% {
		transform: translate3d(0, -2px, 0);
	}
}

@-o-keyframes bounce {
	10%, 26%, 40%, 0%, 50% {
		animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
		transform: translate3d(0, 0, 0);
	}

	20%, 21% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -8px, 0);
	}

	35% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -5px, 0);
	}

	45% {
		transform: translate3d(0, -2px, 0);
	}
}

@keyframes bounce {
	10%, 26%, 40%, 0%, 50% {
		animation-timing-function: cubic-bezier(0.215, 0.61, 0.355, 1);
		transform: translate3d(0, 0, 0);
	}

	20%, 21% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -8px, 0);
	}

	35% {
		animation-timing-function: cubic-bezier(0.755, 0.05, 0.855, 0.06);
		transform: translate3d(0, -5px, 0);
	}

	45% {
		transform: translate3d(0, -2px, 0);
	}
}
  </style>
<% end %>

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/front_page.html.erb
<%# Intentionally blank template required by router for content generated by frontend. %>

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/main_app.html.erb
<h1 class="initial-loading-text">Loading...</h1>
<%# Intentionally blank template required by router for content generated by frontend. %>

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/password_reset.html.erb
<%# Intentionally blank template required by router for content generated by frontend. %>

FarmBot/Software/Farmbot-Web-App/app/views/dashboard/tos_update.html.erb
<%# Intentionally blank template required by router for content generated by frontend. %>